metadata.config:
    profile: Model\Metadata\ProfileMetadataManager
    profile_filter: Model\Metadata\ProfileFilterMetadataManager
    user_filter: Model\Metadata\UserFilterMetadataManager
    content_filter: Model\Metadata\ContentFilterMetadataManager
    default: Model\Metadata\MetadataManager