imports:
    - { resource: config_dev.yml }

support_emails: [%testing_email%, %testing_email%, %testing_email%]

locale.options:
    default: en

dbs.options:
    mysql_social:
        driver: pdo_sqlite
        path: %app_root_dir%/../var/cache/social_data.db
    mysql_brain:
        driver: pdo_sqlite
        path: %app_root_dir%/../var/cache/brain_data.db

neo4j.options:
    host: %db.neo4j.testing.host%
    port: %db.neo4j.testing.port%
    auth: %db.neo4j.testing.auth%
    user: %db.neo4j.testing.user%
    pass: %db.neo4j.testing.pass%

userA.resource: %userA.resource%
userA.access_token: %userA.access_token%
userA.resource_id: %userA.resource_id%
userB.resource: %userB.resource%
userB.access_token: %userB.access_token%
userB.resource_id: %userB.resource_id%

swiftmailer.options:
    disable_delivery: true
