imports:
    - { resource: config_dev.yml }

locale.options:
    default: en

dbs.options:
    mysql_brain:
        driver: pdo_sqlite
        path: %app_root_dir%/../var/cache/brain_data.db

neo4j.options:
    host: %db.neo4j.testing.host%
    port: %db.neo4j.testing.port%
    auth: %db.neo4j.testing.auth%
    user: %db.neo4j.testing.user%
    pass: %db.neo4j.testing.pass%

userA.resource: %userA.resource%
userA.access_token: %userA.access_token%
userA.resource_id: %userA.resource_id%
userB.resource: %userB.resource%
userB.access_token: %userB.access_token%
userB.resource_id: %userB.resource_id%
userC.resource: %userC.resource%
userC.access_token: %userC.access_token%
userC.resource_id: %userC.resource_id%

