validator.config:
    answers: Service\Validator\AnswerValidator
    content_filter: Service\Validator\ContentFilterValidator
    groups: Service\Validator\GroupValidator
    invitations: Service\Validator\InvitationValidator
    profile: Service\Validator\ProfileValidator
    questions: Service\Validator\QuestionsValidator
    tokens: Service\Validator\TokenValidator
    tokenStatus: Service\Validator\TokenStatusValidator
    default: Service\Validator\Validator